from tkinter import *
window = Tk()
window.geometry("600x600")
window.resizable(False, False)
window.title("*says in robotic voice* Password generator interface open.")
frame = LabelFrame(text = "symbols", width = 500, height = 500)
frame.pack()
numbers = BooleanVar()
check_numbers = Checkbutton(frame, text = "0123456789", onvalue = True, offvalue = False, variable = numbers)
check_numbers.pack(padx = 100, pady = 10, anchor = "w")
lowercase = BooleanVar()
check_lowercase = Checkbutton(frame, text = "abcdefghijklmnopqrstuvwxyz", onvalue = True, offvalue = False, variable = lowercase)
check_lowercase.pack(padx = 100, pady = 10, anchor = "w")
uppercase = BooleanVar()
check_uppercase = Checkbutton(frame, text = "ABCDEFGHIJKLMNOPQRSTUVWXYZ", onvalue = True, offvalue = False, variable = uppercase)
check_uppercase.pack(padx = 100, pady = 10, anchor = "w")
symbols = BooleanVar()
check_symbols = Checkbutton(frame, text = "!@#$%^&*()", onvalue = True, offvalue = False, variable = symbols)
check_symbols.pack(padx = 100, pady = 10, anchor = "w")
entry = Entry(frame, width = 40)
entry.pack(padx = 100, pady = 10)
button = Button(frame, text = "Genarate a password", width = 20)
button.pack(padx = 100, pady = 10)
